<?php
	
	/**
	 *  The Contact form gets generated by the ace_form class located in framework/php/class-form-generator.php
	 */
 

	$form_args = array(
		
		"heading" => "<h3>".__('Send us mail','ace_framework')."</h3>",
		"success" => "<h3>".__('Your message has been sent!','ace_framework')."</h3><p>".__('Thank you!','ace_framework')."</p>",
		"submit"  => __('Send','ace_framework'),
		"action"  => get_permalink(),
		"myemail" => ace_get_option('email'),
		"myblogname" => get_option('blogname'),
		"autoresponder" => ace_get_option('autoresponder'),
		"autoresponder_subject" => __('Thank you for your Message!','ace_framework'),
		"autoresponder_email" => ace_get_option('email')
	);
	
	
	
	
	//default elements
	$elements = array(
	
		'username'	=> 	array('type'=>'decoy',	'label'=>'', 'check'=>'must_empty'),										//decoy input field for bots, input field gets hidden, if bot enters value form wont be submitted
	
	);
	
	//user defined elements from backend
	$custom_elements = ace_get_option('contact-form-elements');
	
	if(is_array($custom_elements))
	{
		foreach($custom_elements as $new_element)
		{
			$elements[strtolower( $new_element['label'] ) ] = $new_element;
		}
	}
	
	
	
	$contact_form = new ace_form($form_args);
	$contact_form->create_elements($elements);
	$contact_form->display_form();
	

?>
